### ISSUE TITLE
Any Way to Disable Colors?

### ISSUE THREAD

**Issue by cbougher** [blowmage/minitest-rg#10]
Is there any way to temporarily disable the color output for a particular test run? I need to be able to turn the colors off when running the tests in our Jenkins build system because instead of showing colors it shows the color codes and that makes it difficult to see the test output.

**Comment by grosser** [comment]
@blowmage what do you think about guarding the colorization behind `io.tty?` ?

@cbougher does this work ? `require 'minitest/rg' unless ENV['JENKINS']`

**Comment by blowmage** [comment]
The guidance I've given in the past is to put a guard condition on the require.

```ruby
require "minitest/rg" unless ENV["NOCOLOR"]
```

However, Ryan just [added a guard](https://github.com/seattlerb/minitest/blob/d74e13981aa108ea96f97adfea81696f8d5a32d6/lib/minitest/pride_plugin.rb#L16) to minitest/pride and we should follow.

**Comment by grosser** [comment]
@cbougher PR time ?

**Comment by blowmage** [comment]
No, I'm gonna push a change very soon.

**Comment by grosser** [comment]
thx!

**Comment by blowmage** [comment]
Please upgrade to the 5.2.0 release.
