### ISSUE TITLE
Add `--rg` option to run with Red Green

### ISSUE THREAD

**Issue by blowmage** [blowmage/minitest-rg#11]
Wouldn't it be nice?

```ruby
module MiniTest
  def self.plugin_color_options opts, options # :nodoc:
    opts.on "--rg", "Add red/green to test output." do
      Color.color!
    end
  end
end
```

**Comment by grosser** [comment]
Having to give an extra option to enable redgreen or enabling rg for projects that did not require it ?
My projects all have Gemfiles ... so there is no accidental rg in there to catch that option ... so this would not help ...

**Comment by blowmage** [comment]
If you have minitest-rg required in your test or auto-required by Bundker in your Gemfile you don't need to do anything else. The flag option is only for when you have the minitest-rg gem installed on your system and you want to enable it from the terminal when running your tests.

**Comment by grosser** [comment]
I don't have that issue / situation ... so idk ... sounds useless to me :)

**Comment by blowmage** [comment]
It's okay if you don't need or use it. :)
